### ISSUE TITLE
Update Readme to state where files should be extracted to

### ISSUE THREAD

**Issue by windy54** [bennuttall/bett-bot#1]
As a new comer to Flask it took me a while to understand why I could not get the app to work, eventually I realised it was because I had extracted the files to a folder called bett-bot and was running the script from that folder.

I had created a folder /home/pi/web/static/photos so pictures were being taken and displayed when the web page was re-loaded but not when a new one was taken.

It was only after trying to create my own app I realised what I had been doing wrong.

Suggest the instructions are modified to include the following at a suitable point.
1) create a folder /home/pi/web
2) extract the files into the web folder
3) create a folder /home/pi/web/static/photos
4) run the app from the web folder

**Comment by bennuttall** [comment]
Thanks for the report! I hurriedly added the instructions to the readme without checking.

I've made it so it uses a relative file path rather than the hard-coded one, so it should work from wherever you place the app folder.

I also created the empty\* `photos` folder so it won't be necessary to create this yourself.

I also need to remove the dependency on the Twitter `Twython` library as you can use the app without the Twitter feature. I'll do that in the next commiit.

*git doesn't allow empty folders, so I added a `.gitignore` to tell it to ignore any `jpg` files in that folder.
